-- AlterTable
ALTER TABLE `follower` ALTER COLUMN `updateAt` DROP DEFAULT;

-- AlterTable
ALTER TABLE `story` ALTER COLUMN `updateAt` DROP DEFAULT;

-- AlterTable
ALTER TABLE `user` ALTER COLUMN `updateAt` DROP DEFAULT;

-- CreateTable
CREATE TABLE `Like` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `SenderId` INTEGER NOT NULL,
    `StoryId` INTEGER NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Like` ADD CONSTRAINT `Like_SenderId_fkey` FOREIGN KEY (`SenderId`) REFERENCES `User`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Like` ADD CONSTRAINT `Like_StoryId_fkey` FOREIGN KEY (`StoryId`) REFERENCES `Story`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;
